version: "3.8"
name: vialmentor-backend
services:
  api:
    build:
      context: ../src/api
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ../.data/api:/data
      - ../.data/ingest:/docs
    environment:
      - ConnectionStrings__ChatsDb="Data Source=/data/chats.db;"
      - Services__Deepseek__ApiKey=${DEEPSEEK_API_KEY}
      - Services__TextProcessor__BaseUrl="http://text-processor:5001"
      - Services__ContextRepository__ChromaUri="http://localhost:5002/api/v1/"
      - Services__ContextRepository__ContextCollection=context_documents
      - Services__ContextRepository__FragmentCollection=fragments
      - Services__ContextSeeder__SeedDirectory=/docs
      
  text-processor:
    build:
      context: ../src/text_processor
      dockerfile: Dockerfile
    ports:
      - "5001:5000"

  context-storage:
    image: chromadb/chroma:0.6.2
    volumes:
      - ../.data/context-storage:/chroma/chroma
    ports:
      - "5002:8000"

  